# Generated by Django 5.1.7 on 2025-03-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Starting point of the route', max_length=255)),
                ('destination', models.CharField(help_text='Ending point of the route', max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=6)),
                ('estimated_time', models.DurationField(help_text='Estimated travel time (hh:mm:ss)')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depature_time', models.TimeField(help_text='Time when bus start')),
                ('arrival_time', models.TimeField(help_text='Expected  arrival time')),
                ('date', models.DateTimeField(help_text='Date of the journey (Y-M-D)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ticket price', max_digits=8)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
        ),
    ]
