# Generated by Django 5.1.7 on 2025-03-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='depature_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='Time when bus starts', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.TimeField(blank=True, help_text='Expected arrival time', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(help_text='Date and time of the journey (Y-M-D H:M:S)'),
        ),
    ]
