# Generated by Django 5.1.7 on 2025-03-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_remove_schedule_depature_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='estimated_time',
            field=models.TimeField(help_text='Estimated travel time (hh:mm:ss)', null=True),
        ),
    ]
