# Generated by Django 5.1.7 on 2025-03-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_remove_busadmin_address_remove_busadmin_company_name_and_more'),
        ('route', '0003_alter_route_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bus_admin',
            field=models.ForeignKey(blank=True, help_text='Assigned Bus Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus.busadmin'),
        ),
    ]
