# Generated by Django 5.1.7 on 2025-03-09 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_busadmin_booked_seats_busadmin_destination_and_more'),
        ('route', '0004_schedule_bus_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_departure', models.DateTimeField(help_text='Scheduled departure time of the bus')),
                ('scheduled_arrival', models.DateTimeField(help_text='Scheduled arrival time of the bus')),
                ('actual_departure', models.DateTimeField(blank=True, help_text='Actual departure time of the bus', null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, help_text='Actual arrival time of the bus', null=True)),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('delayed', 'Delayed'), ('completed', 'Completed')], default='on_time', help_text='Current status of the trip', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('driver', models.ForeignKey(help_text='Driver of the bus', on_delete=django.db.models.deletion.CASCADE, to='bus.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
        ),
    ]
