# Generated by Django 5.1.7 on 2025-03-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='bus_admin',
        ),
    ]
