# Generated by Django 5.1.7 on 2025-03-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_remove_schedule_bus_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.DateTimeField(blank=True, help_text='Expected arrival time', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Date and time of the journey (Y-M-D H:M:S)', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.DateTimeField(blank=True, help_text='Time when bus starts', null=True),
        ),
    ]
