# Generated by Django 5.1.7 on 2025-03-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_alter_schedule_arrival_time_alter_schedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Date and time of the journey (Y-M-D H:M:S)', null=True),
        ),
    ]
