# Generated by Django 5.1.7 on 2025-03-12 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0009_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
    ]
