# Generated by Django 5.1.7 on 2025-03-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0010_customerreview_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='route-img/'),
        ),
    ]
