# Generated by Django 5.1.7 on 2025-03-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0052_bus_ticket_counter_busreservation_ticket_counter_and_more'),
        ('route', '0011_route_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ticket_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.ticketcounter'),
        ),
    ]
