# Generated by Django 5.1.7 on 2025-03-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0012_schedule_ticket_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
