# Generated by Django 5.1.7 on 2025-04-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0014_schedule_transportation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='estimated_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated travel time in Hour', null=True),
        ),
    ]
