# Generated by Django 5.1.7 on 2025-04-11 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0015_alter_route_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.schedule'),
        ),
    ]
