# Generated by Django 5.1.7 on 2025-04-11 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0062_buslayout_bus'),
        ('route', '0017_trip_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.staff'),
        ),
    ]
