# Generated by Django 5.1.7 on 2025-04-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0018_trip_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Number of available seats', null=True),
        ),
    ]
