# Generated by Django 5.1.7 on 2025-04-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0020_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='ticket_counter',
        ),
    ]
