# Generated by Django 5.1.7 on 2025-05-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0021_remove_schedule_ticket_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='available_seats',
            field=models.PositiveIntegerField(default=0, help_text='Number of available seats'),
        ),
    ]
