# Generated by Django 5.1.7 on 2025-06-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0022_alter_schedule_available_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='sub_routes',
            field=models.ManyToManyField(blank=True, to='route.subroutes'),
        ),
    ]
