# Generated by Django 5.1.7 on 2025-06-01 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0023_subroutes_route_sub_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='route',
            name='estimated_time',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='SeachSubRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveBigIntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
                ('subroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.subroutes')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'subroute')},
            },
        ),
    ]
