# Generated by Django 5.1.7 on 2025-06-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0024_alter_route_destination_alter_route_distance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeachSubRoute',
            new_name='SearchSubRoute',
        ),
    ]
