# Generated by Django 5.1.7 on 2025-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0025_rename_seachsubroute_searchsubroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cut_price',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=8),
            preserve_default=False,
        ),
    ]
