# Generated by Django 5.1.7 on 2025-06-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0026_schedule_cut_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='cut_price',
            new_name='original_price',
        ),
    ]
