# Generated by Django 5.1.7 on 2025-06-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0027_rename_cut_price_schedule_original_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='original_price',
            new_name='sales_price',
        ),
    ]
