# Generated by Django 5.1.7 on 2025-06-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0028_rename_original_price_schedule_sales_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='sales_price',
            new_name='sale_price',
        ),
    ]
