# Generated by Django 5.1.7 on 2025-06-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0029_rename_sales_price_schedule_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
