# Generated by Django 5.1.7 on 2025-06-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0030_route_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='period',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('night', 'Night')], max_length=5, null=True),
        ),
    ]
