# Generated by Django 5.1.7 on 2025-06-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0031_schedule_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='period',
            new_name='shift',
        ),
    ]
