# Generated by Django 5.1.7 on 2025-03-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0010_userotp_phone_alter_userotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='temp_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
