# Generated by Django 5.1.7 on 2025-03-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0012_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField(max_length=10)),
                ('image', models.ImageField(upload_to='system_logo/')),
            ],
        ),
    ]
