# Generated by Django 5.1.7 on 2025-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0013_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='address',
            field=models.CharField(default='Kathmandu Gwarko', max_length=100),
            preserve_default=False,
        ),
    ]
