# Generated by Django 5.1.7 on 2025-03-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0015_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location_name', models.CharField(max_length=20)),
                ('longitute', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=16)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_image/')),
            ],
        ),
    ]
