# Generated by Django 5.1.7 on 2025-03-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0018_transportationcompany_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationcompany',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
