# Generated by Django 5.1.7 on 2025-03-31 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0019_transportationcompany_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationcompany',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportation_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
