# Generated by Django 5.1.7 on 2025-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0020_alter_transportationcompany_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
