# Generated by Django 5.1.7 on 2025-05-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0021_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
