# Generated by Django 5.1.7 on 2025-06-04 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0022_alter_system_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='transportationcompany',
            name='agent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_user.agent'),
        ),
    ]
