# Generated by Django 5.1.7 on 2025-03-10 07:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_booking_status_booking_schedule'),
        ('bus', '0008_busadmin_booked_seats_busadmin_destination_and_more'),
        ('route', '0008_alter_schedule_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings of one bus', max_digits=10)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0.0, help_text='Total commission deducted', max_digits=10)),
                ('bus', models.ForeignKey(help_text='Bus associated with commission', on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of paid', max_digits=10)),
                ('commission_deducted', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission deducted from payment', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('trip', models.ForeignKey(help_text='The trip for which the payment was made', on_delete=django.db.models.deletion.CASCADE, to='route.trip')),
                ('user', models.ForeignKey(help_text='User who made payment', limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=10, help_text='Rate for commission', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rate',), name='unique_rate')],
            },
        ),
    ]
