# Generated by Django 5.1.7 on 2025-03-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_paid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'number')},
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.seat', unique=True),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='bus',
        ),
    ]
