# Generated by Django 5.1.7 on 2025-03-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_payment_trip_payment_schedule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(default='A1', help_text="Seat number in the format 'A1'", max_length=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='seat',
            name='number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
    ]
