# Generated by Django 5.1.7 on 2025-03-22 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_seat_unique_together_seat_seat_number_and_more'),
        ('bus', '0032_busreservation_driver_busreservation_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='bus_reserve',
            field=models.ForeignKey(blank=True, help_text='Bus associated with commission', null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.busreservation'),
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('bus', 'Bus'), ('bus_reservation', 'Bus Reservation')], default='bus', help_text='Type of commission', max_length=25),
        ),
        migrations.AlterField(
            model_name='commission',
            name='bus',
            field=models.ForeignKey(blank=True, help_text='Bus associated with commission', null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.bus'),
        ),
    ]
