# Generated by Django 5.1.7 on 2025-03-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_commission_bus_reserve_commission_commission_type_and_more'),
        ('bus', '0035_alter_bus_features_alter_bus_is_running_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(blank=True, help_text='Bus to which the seat belongs', null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.bus'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='bus_reserve',
            field=models.ForeignKey(blank=True, help_text='Bus reservation associated with commission', null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.busreservation'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('seat_number', 'bus')},
        ),
        migrations.CreateModel(
            name='BusLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('aisle_column', models.PositiveIntegerField()),
                ('layout_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.OneToOneField(blank=True, help_text='Bus associated with this layout', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='bus.bus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
