# Generated by Django 5.1.7 on 2025-03-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_seat_bus_alter_commission_bus_reserve_and_more'),
        ('bus', '0043_busreservation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bus_reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.busreservation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.seat'),
        ),
    ]
