# Generated by Django 5.1.7 on 2025-03-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_busreservationbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bus_reserve',
        ),
        migrations.AlterField(
            model_name='busreservationbooking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('available', 'Available')], default='booked', max_length=20),
        ),
    ]
