# Generated by Django 5.1.7 on 2025-03-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_booking_bus_reserve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('reserved', 'Reserved'), ('canceled', 'Canceled')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='booked', max_length=10),
        ),
    ]
