# Generated by Django 5.1.7 on 2025-03-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_booking_paid_booking_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('khalti', 'Khalti'), ('esewa', 'Esewa')], max_length=20, null=True),
        ),
    ]
