# Generated by Django 5.1.7 on 2025-03-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remove_payment_schedule_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
    ]
