# Generated by Django 5.1.7 on 2025-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_payment_payment_status_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'Esewa')], default='khalti', max_length=20),
        ),
    ]
