# Generated by Django 5.1.7 on 2025-03-27 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_remove_payment_bus_payment_payment_status'),
        ('bus', '0051_alter_driver_driver_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.bus'),
        ),
    ]
