# Generated by Django 5.1.7 on 2025-03-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_payment_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
