# Generated by Django 5.1.7 on 2025-04-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_delete_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('canceled', 'Canceled')], default='pending', max_length=25),
        ),
    ]
