# Generated by Django 5.1.7 on 2025-04-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='busreservationbooking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
