# Generated by Django 5.1.7 on 2025-04-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_remove_booking_payment_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bus',
        ),
    ]
