# Generated by Django 5.1.7 on 2025-04-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_remove_payment_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
    ]
