# Generated by Django 5.1.7 on 2025-04-09 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_remove_payment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.rate'),
        ),
    ]
