# Generated by Django 5.1.7 on 2025-04-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_payment_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusLayout',
        ),
    ]
