# Generated by Django 5.1.7 on 2025-04-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_delete_buslayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservationbooking',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='busreservationbooking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
