# Generated by Django 5.1.7 on 2025-04-29 06:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_busreservationbooking_agreed_price_and_more'),
        ('route', '0020_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='rate',
        ),
        migrations.AddField(
            model_name='commission',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Rate for commission', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='commission',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.schedule'),
        ),
        migrations.AddField(
            model_name='payment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.schedule'),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
