# Generated by Django 5.1.7 on 2025-04-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_remove_payment_rate_commission_rate_and_more'),
        ('bus', '0070_alter_seatlayoutbooking_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='commission',
            name='bus',
            field=models.ForeignKey(blank=True, help_text='Bus associated with commission', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='bus.bus'),
        ),
    ]
