# Generated by Django 5.1.7 on 2025-05-06 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_alter_booking_bus_alter_booking_schedule_and_more'),
        ('bus', '0070_alter_seatlayoutbooking_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busreservationbooking',
            name='bus_reserve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_booking', to='bus.busreservation'),
        ),
    ]
