# Generated by Django 5.1.7 on 2025-05-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0039_alter_busreservationbooking_bus_reserve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='booking',
            new_name='payment',
        ),
    ]
