# Generated by Django 5.1.7 on 2025-05-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_rename_booking_payment_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment',
            new_name='booking',
        ),
    ]
