# Generated by Django 5.1.7 on 2025-06-03 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_rename_payment_payment_booking'),
        ('route', '0025_rename_seachsubroute_searchsubroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.schedule'),
        ),
    ]
