# Generated by Django 5.1.7 on 2025-06-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_alter_commission_schedule'),
        ('bus', '0074_alter_bus_total_seats'),
        ('custom_user', '0024_agent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_user.agent'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='bus',
            field=models.ForeignKey(blank=True, help_text='Bus associated with commission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission', to='bus.bus'),
        ),
    ]
