# Generated by Django 5.1.7 on 2025-06-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_commission_agent_alter_commission_bus'),
        ('bus', '0074_alter_bus_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='bus.bus'),
        ),
    ]
