# Generated by Django 5.1.7 on 2025-06-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_alter_booking_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='boarding_point',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
