# Generated by Django 5.1.7 on 2025-06-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_booking_boarding_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
