# Generated by Django 5.1.7 on 2025-06-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_booking_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
