# Generated by Django 5.1.7 on 2025-06-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_remove_payment_transaction_id'),
        ('custom_user', '0024_agent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='transportation_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_user.transportationcompany'),
        ),
    ]
