# Generated by Django 5.1.7 on 2025-06-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_alter_commission_transportation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_phone',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
