# Generated by Django 5.1.7 on 2025-03-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(help_text='Example: BA 1 KHA 1234', max_length=20, unique=True)),
                ('bus_type', models.CharField(choices=[('tourist_bus', 'Tourist Bus'), ('express_bus', 'Express Bus'), ('deluxe_bus', 'Deluxe Bus'), ('mini_bus', 'Mini Bus'), ('micro_bus', 'Micro Bus'), ('electric_bus', 'Electric Bus')], default='deluxe_bus', max_length=20)),
                ('bus_image', models.ImageField(upload_to='bus_images/')),
                ('total_seats', models.PositiveIntegerField(default=35)),
                ('available_seats', models.PositiveIntegerField(default=35)),
                ('is_active', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False, help_text='To ensure the bus is in running state or not')),
            ],
        ),
        migrations.CreateModel(
            name='BusAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('driver_profile', models.ImageField(upload_to='driver_profile/')),
                ('license_image', models.ImageField(upload_to='driver_license/')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('staff_profile', models.ImageField(blank=True, null=True, upload_to='staff_profile/')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
