# Generated by Django 5.1.7 on 2025-03-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_admin',
        ),
    ]
