# Generated by Django 5.1.7 on 2025-03-08 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_remove_bus_bus_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='TicketCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'sub_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='tickert_counter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
