# Generated by Django 5.1.7 on 2025-03-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_ticketcounter_counter_name_ticketcounter_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busadmin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='busadmin',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='busadmin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='busadmin',
            name='license_number',
        ),
        migrations.AddField(
            model_name='busadmin',
            name='bus',
            field=models.OneToOneField(blank=True, help_text='Bus assigned to  this admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus.bus'),
        ),
    ]
