# Generated by Django 5.1.7 on 2025-03-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_feature_bus_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(blank=True, choices=[('ac', 'AC'), ('electricity', 'Electricity'), ('fan', 'Fan')], max_length=50, null=True),
        ),
    ]
