# Generated by Django 5.1.7 on 2025-03-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_alter_feature_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='features',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddField(
            model_name='bus',
            name='features',
            field=models.CharField(choices=[('ac', 'AC'), ('electricity', 'Electricity'), ('fan', 'Fan')], default=True, max_length=20, null=True),
        ),
    ]
