# Generated by Django 5.1.7 on 2025-03-12 15:17

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_remove_bus_features_delete_feature_bus_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ac', 'AC'), ('electricity', 'Electricity'), ('fan', 'Fan'), ('wifi', 'Wifi')], max_length=23, null=True),
        ),
    ]
