# Generated by Django 5.1.7 on 2025-03-12 15:39

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0012_alter_bus_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ac', 'AC'), ('charging', 'charging'), ('fan', 'Fan'), ('wifi', 'Wifi')], max_length=20, null=True),
        ),
    ]
