# Generated by Django 5.1.7 on 2025-03-14 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0013_alter_bus_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcounter',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'sub_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_counter', to=settings.AUTH_USER_MODEL),
        ),
    ]
