# Generated by Django 5.1.7 on 2025-03-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0016_alter_bus_driver_alter_bus_staff'),
        ('route', '0010_customerreview_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
    ]
