# Generated by Django 5.1.7 on 2025-03-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0018_busreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busreservation',
            old_name='_state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='busreservation',
            old_name='customer',
            new_name='user',
        ),
    ]
