# Generated by Django 5.1.7 on 2025-03-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0019_rename__state_busreservation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
    ]
