# Generated by Django 5.1.7 on 2025-03-19 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0022_remove_busadmin_route_bus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.staff'),
        ),
    ]
