# Generated by Django 5.1.7 on 2025-03-19 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0023_alter_bus_staff'),
        ('route', '0010_customerreview_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.staff'),
        ),
    ]
