# Generated by Django 5.1.7 on 2025-03-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0024_alter_bus_route_alter_bus_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busreservation',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=10),
        ),
    ]
