# Generated by Django 5.1.7 on 2025-03-21 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_seat_unique_together_seat_seat_number_and_more'),
        ('bus', '0028_staff_staff_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.commission'),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
