# Generated by Django 5.1.7 on 2025-03-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0029_busreservation_commission_busreservation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busreservation',
            name='commission',
        ),
    ]
