# Generated by Django 5.1.7 on 2025-03-22 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0030_remove_busreservation_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='VechicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='busreservation',
            name='bus',
        ),
        migrations.AddField(
            model_name='busreservation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.vechicletype'),
        ),
    ]
