# Generated by Django 5.1.7 on 2025-03-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0031_vechicletype_remove_busreservation_bus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.driver'),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.staff'),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='vechicle_number',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
