# Generated by Django 5.1.7 on 2025-03-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0032_busreservation_driver_busreservation_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busreservation',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], max_length=10),
        ),
    ]
