# Generated by Django 5.1.7 on 2025-03-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0033_alter_busreservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busreservation',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], max_length=10, null=True),
        ),
    ]
