# Generated by Django 5.1.7 on 2025-03-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0035_alter_bus_features_alter_bus_is_running_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busreservation',
            name='user',
        ),
        migrations.AlterField(
            model_name='bus',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the bus is active'),
        ),
        migrations.AlterField(
            model_name='busreservation',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('available', 'available')], default='available', max_length=10, null=True),
        ),
    ]
