# Generated by Django 5.1.7 on 2025-03-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0037_busreservation_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busreservation',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('available', 'Available')], default='available', max_length=10, null=True),
        ),
    ]
