# Generated by Django 5.1.7 on 2025-03-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0038_alter_busreservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vechicle_images/'),
        ),
        migrations.AlterField(
            model_name='busreservation',
            name='reservation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busreservation',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('available', 'Available')], default='available', max_length=10),
        ),
    ]
