# Generated by Django 5.1.7 on 2025-03-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0039_busreservation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vechicletype',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='vechicle_type_images/'),
        ),
    ]
