# Generated by Django 5.1.7 on 2025-03-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0040_vechicletype_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vechicletype',
            old_name='images',
            new_name='image',
        ),
    ]
