# Generated by Django 5.1.7 on 2025-03-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0041_rename_images_vechicletype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='vechicle_model',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
