# Generated by Django 5.1.7 on 2025-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0042_busreservation_color_busreservation_vechicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
