# Generated by Django 5.1.7 on 2025-03-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0043_busreservation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busreservation',
            old_name='reservation_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='busreservation',
            name='destination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
