# Generated by Django 5.1.7 on 2025-03-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0045_remove_busreservation_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusReservationBooking',
        ),
    ]
