# Generated by Django 5.1.7 on 2025-03-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0046_delete_busreservationbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
