# Generated by Django 5.1.7 on 2025-03-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0047_busreservation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busreservation',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='busreservation',
            name='source',
        ),
    ]
