# Generated by Django 5.1.7 on 2025-03-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0048_remove_busreservation_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buslayout',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus'),
        ),
    ]
