# Generated by Django 5.1.7 on 2025-03-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0049_alter_buslayout_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcounter',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Bank account number for payments', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketcounter',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of the bank', max_length=100, null=True),
        ),
    ]
