# Generated by Django 5.1.7 on 2025-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0050_ticketcounter_bank_account_ticketcounter_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_profile',
            field=models.ImageField(blank=True, null=True, upload_to='driver_profile/'),
        ),
    ]
