# Generated by Django 5.1.7 on 2025-03-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0053_busreservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='vechicle_document/'),
        ),
    ]
