# Generated by Django 5.1.7 on 2025-03-31 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0054_busreservation_document'),
        ('custom_user', '0017_rename_longitute_transportationcompany_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='transportation_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_user.transportationcompany'),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='transportation_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_user.transportationcompany'),
        ),
    ]
