# Generated by Django 5.1.7 on 2025-03-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0055_bus_transportation_company_and_more'),
        ('custom_user', '0018_transportationcompany_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='transportation_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_user.transportationcompany'),
        ),
        migrations.AddField(
            model_name='staff',
            name='transportation_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_user.transportationcompany'),
        ),
    ]
