# Generated by Django 5.1.7 on 2025-04-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0056_driver_transportation_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='is_running',
        ),
    ]
