# Generated by Django 5.1.7 on 2025-04-08 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0058_remove_driver_ticket_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busadmin',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.driver'),
        ),
    ]
