# Generated by Django 5.1.7 on 2025-04-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0059_alter_busadmin_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busreservation',
            name='status',
        ),
    ]
