# Generated by Django 5.1.7 on 2025-04-11 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0060_remove_busreservation_status'),
        ('route', '0016_trip_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buslayout',
            name='bus',
        ),
        migrations.AddField(
            model_name='buslayout',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.schedule'),
        ),
    ]
