# Generated by Django 5.1.7 on 2025-04-21 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0062_buslayout_bus'),
        ('route', '0019_schedule_available_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
        migrations.CreateModel(
            name='SeatLayoutBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
