# Generated by Django 5.1.7 on 2025-04-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0063_remove_bus_available_seats_remove_bus_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buslayout',
            name='schedule',
        ),
    ]
