# Generated by Django 5.1.7 on 2025-04-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0064_remove_buslayout_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
