# Generated by Django 5.1.7 on 2025-04-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0065_busreservation_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='ticket_counter',
        ),
        migrations.RemoveField(
            model_name='busreservation',
            name='ticket_counter',
        ),
    ]
