# Generated by Django 5.1.7 on 2025-04-29 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0066_remove_bus_ticket_counter_and_more'),
        ('route', '0020_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatlayoutbooking',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.schedule'),
        ),
    ]
