# Generated by Django 5.1.7 on 2025-04-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0067_alter_seatlayoutbooking_schedule'),
        ('route', '0020_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatlayoutbooking',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.schedule'),
        ),
    ]
