# Generated by Django 5.1.7 on 2025-05-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0070_alter_seatlayoutbooking_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='price_range',
            field=models.CharField(default='0-0', max_length=20),
        ),
    ]
