# Generated by Django 5.1.7 on 2025-05-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0071_busreservation_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Electric', 'Electric'), ('Disel', 'Disel'), ('Petrol', 'Petrol')], max_length=50, null=True),
        ),
    ]
