# Generated by Django 5.1.7 on 2025-06-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0072_busreservation_fuel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bus',
            name='features',
        ),
        migrations.DeleteModel(
            name='TicketCounter',
        ),
        migrations.AddField(
            model_name='bus',
            name='features',
            field=models.ManyToManyField(blank=True, to='bus.busfeatures'),
        ),
    ]
