# Generated by Django 5.1.7 on 2025-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0073_busfeatures_remove_bus_features_delete_ticketcounter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
