# Generated by Django 5.1.7 on 2025-06-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0074_alter_bus_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busfeatures',
            name='name',
            field=models.CharField(choices=[('AC', 'AC'), ('Wifi', 'WiFi'), ('TV', 'TV'), ('Charging', 'Charging Port'), ('Water', 'Water Bottle'), ('Blanket', 'Blanket'), ('GPS', 'GPS Tracking'), ('ReadingLight', 'Reading Light'), ('ReclinerSeat', 'Recliner Seat'), ('Toilet', 'Toilet'), ('Snacks', 'Snacks Provided'), ('Curtains', 'Curtains'), ('FirstAid', 'First Aid Kit'), ('CCTV', 'CCTV Surveillance'), ('Music', 'Music System'), ('FootRest', 'Foot Rest'), ('Fan', 'Fan'), ('WindowSeat', 'Window Seat'), ('EmergencyExit', 'Emergency Exit'), ('SecurityGuard', 'Security Guard'), ('Heater', 'Heater'), ('DoubleDecker', 'Double Decker'), ('Luxury', 'Luxury Coach'), ('AdjustableHeadrest', 'Adjustable Headrest')], max_length=50, unique=True),
        ),
    ]
