# Generated by Django 5.1.7 on 2025-06-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0075_alter_busfeatures_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='busfeatures',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='bus_features_icons/'),
        ),
    ]
