# Generated by Django 5.1.7 on 2025-06-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0076_busfeatures_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='contact_number',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
