# Generated by Django 5.1.7 on 2025-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0077_bus_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
